services:
  flaskserver:
    build: ./flask_server/
    command: sh -c "sleep 10s ; python3 ./run.py"
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    build: ./db_service/
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306' 